apiVersion: 1

datasources:
  - name: Prometheus
    uid: forge-prometheus
    type: prometheus
    access: proxy
    url: http://${PROMETHEUS_HOST}:${PROMETHEUS_PORT}
    isDefault: false
    jsonData:
      httpMethod: POST
      timeInterval: 15s
