version: 2
sources:
- name: bronze
  database: default
  tables:
  - name: ci_checks
    identifier: bronze___ci_checks
  - name: human_interactions
    identifier: bronze___human_interactions
  - name: jira_tickets
    identifier: bronze___jira_tickets
  - name: llm_traces
    identifier: bronze___llm_traces
  - name: pull_requests
    identifier: bronze___pull_requests
